### ISSUE TITLE
Compilation using resolve.js is currently broken

### ISSUE THREAD

**Issue by ironmanwaring** [sweetskills/swagger#2]
@everythingbiig can you look at this?  It looks like you added several new commands and a new folder structure which have broken the swagger.json build - when i download from my last commit the build runs successfully

**Comment by everythingbiig** [comment]
Looking into it.

**Comment by everythingbiig** [comment]
Checked in changes to fix references in swagger spec.  Validated resulting json and confirmed no syntax errors.
